server:
  port: 9527
spring:
  application:
    name: microservicecloud-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance: 
    instance-id: gateway-9527.com
    prefer-ip-address: true  
zuul: 
  ignored-services: "*" #忽略所有微服务
  prefix: /lzy
  routes:
    mydept: 
      service-id: microservicecloud-dept  #真实微服务
      path: /mydept/** #替代的微服务
    
info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: microservicecloud-zuul-gateway-9527
  build.version: 0.0.1-SNAPSHOT